### ISSUE TITLE
:books: Add a colophon

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2018.djangocon.us#101]
We should have a colophon and give credit like [PyCon AU](https://2018.pycon-au.org/colophon/) does for passing on goodwill from others who have inspired us.

**Comment by williln** [comment]
Here's a start: 

## Website Copy 

We are grateful to the past organizers of DjangoCon US and of other events for their help and inspiration, in particular but not limited to: 

- [Geek Feminism Wiki](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy) (Code of Conduct) 
- [AlterConf](https://www.alterconf.com/speak) (speaker slide guidelines) 
- [DjangoCon Europe](https://2016.djangocon.eu), Code of Conduct Transparency Report 

## Website Design 

This website is based on free and open source software, and was designed by our friends at [YupGup](http://yupgup.com/). 

- [Jekyll](https://jekyllrb.com/) 
- [Foundation](https://foundation.zurb.com/sites/docs/) 
- [PyCon Australia](https://2018.pycon-au.org/colophon/) (for this colophon) 

## Image Credits 

- [Group visit to ENIAC](https://www.flickr.com/photos/144080672@N05/28810970252/in/album-72157672216515946/), Bartek Pawlik, CC BY-NC 2.0
- [Spokane Crowd](https://www.flickr.com/photos/144080672@N05/36937531752/), Adam Fast, with permission 
- [San Diego Marriott Mission Valley](https://www.marriott.com/hotels/travel/sanmv-san-diego-marriott-mission-valley/), courtesy of the hotel
