### ISSUE TITLE
:calendar: Add financial aid decision notifications date to page

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2018.djangocon.us#103]
We currently state "Decision notifications will be sent on July 9th, 2018." on our financial aid [application page](https://docs.google.com/forms/d/e/1FAIpQLSfqOQJNXDSftszH5Ar_LQT6Y0IcvuRUaXTC9ERS6h6PTKsvHg/viewform) we should make sure it exists on our [Financial Aid page](https://2018.djangocon.us/financial-aid/) too along with any other common questions we missed.

**Comment by williln** [comment]
@jefftriplett  I think this can be closed: 
<img width="1016" alt="screen shot 2018-06-05 at 8 34 00 am" src="https://user-images.githubusercontent.com/2286304/40986521-3ea2aee6-689b-11e8-9012-4b5edfb9d70b.png">

Unless there are other questions that need answering?

**Comment by jefftriplett** [comment]
I really don't want to miss it for next year since it came up a few times.
