### ISSUE TITLE
Content Updates

### ISSUE THREAD

**Issue by KatherineMichel** [djangocon/2018.djangocon.us#13]
## Homepage
- [x] Update Buy Tickets link (link coming soon)
- [x] Update Be a Volunteer sign up link (replaced with speaking page link)
- [x] Update sponsors
- [x] Replace blog post cards (new blog posts coming soon, replace remaining one)
- [x] Social media icons in footer open in new window, inconsistent with other links

## About
- [x] Replace Pre-Conference dates (commented out)
- [x] Update Commitment to Diversity card year
- [x] See full schedule link (commented out)
- [x] Update Financial Aid card closing date (commented out)
- [x] Day 1 Orientation- assuming this is happening again. "More details coming in the blog." (Update: Kojo indicated to leave this in)

### Note from Kati
Commitment to Diversity section now links to CoC, not Venue Accessibility. 

## Tickets
- [x] Update Buy Tickets now button link (commented out)
- [x] Don't Forget box has a date (correct?) and dummy text to update or remove
- [x] Ticket price policy/timeline correct?
- [x] Refund policy/timeline correct? (commented out)

### Notes from Catherine about Tickets page

Changed location, but dates and prices need to be changed, and also I don’t think the claim that the conference sold out the past two years is accurate anymore

## FAQs

- [x] Update tickets link (5 instance in Tickets section) --> Links to `/tickets/` (Lacey)
- [x] Update Slack channel link in Schedule section --> Deleted link, will add new one when we open this year's Slack. (Lacey)
- [x] Will have broken blog post link for child care in Accessibility section --> Deleted link (Lacey)

## CoC
- [x] Is DEFNA phone number still accurate in Need help? box?  (commented out)
- [x] Make sure that we have covered everything relevant in Important Numbers section
- [x] Update Code of Conduct Team section, if change  (commented out)
- [x] Update Code of Conduct link in License section, preferably not hard coded

### Notes from Catherine about CoC page
- [x] Is the code of conduct team the same (Lacey, Kojo, Heather, and you?) --> Deleted specific members; will add back closer to conference (Lacey)
- [x] This had a lot of Spokane specific information that I changed, the police helpline and tip line numbers
- [x] They do not seem to have any way to text the police, so I deleted that line.
- [ ] I wanted to add this but wasn’t quite sure how: To access 9-1-1 from a cell phone or outside San Diego, call (619) 531-2065.”
- [x] The closest hospital didn’t seem to have much of a website, but I linked what I could.

## Financial Aid
- [x] Financial aid policy correct? --> Confirmed with FA chair (Lacey)
- [x] 4 sections about applying for financial aid (commented out)

Why DjangoCon US- will leave this alone for now because subject to change

## Organizers
- [x] Update organizer cards, as needed, are links still accurate?
- [ ] Obtain photos to replace placeholders

## Schedule/Tutorials/Talks/Sprints
- [x] Update timings, Talk and Tutorials links/cards --> All cards deleted; will add new ones when we have a new schedule (Lacey)

### Notes from Catherine about Schedule/Tutorials/Talks/Sprints pages
Schedule- I replaced the old dates with correct dates. Sunday through Friday still lined up, of course
Tutorials- changed year and date
Sprints- changed month, date, and year

## Venue
- [x]  Update map in frame/hyperlink and View Larger Map hyperlink
- [x]  Update hotel pic
- [x]  Update info and date (accurate/complete?)
- [x]  Update Book a Room link
- [x]  Update Around San Diego to local info
- [x]  Update An Accessible Experience info to correct hotel
- [x]  Update An Accessible Experience info in box to local info (accurate/complete?) --> Will make separate ticket; commented out in meantime (Lacey)

### Note from Kati
Some links on venue page are also opening in new windows, do we want to change this?
Hotel info still sparse; Is Accessible Experience info accurate/complete?

> I think them opening in new windows is fine, but we can change it if you want? Just open a new ticket and assign it to me and I can take care of it. Re: accessibility-- I'll open a new ticket for that one. (Lacey) 

### Notes from Catherine about Venue page
Most of this information needs to be changed, much of which I don’t have currently.
I made changes up to row 24, though more specific rewrites may be wanted. It really is right next to a running trail, so I copied most of that exactly from last year.

## Room and Ride Sharing
- [x] Update hotel and other local info
- [x] Update spreadsheet link (2 places)

## Speaking
- [x] Update dates (commented out)
- [x] 2 CFP, speaker resource, financial aid sections (commented out)
- [x] Looks like Talk and Tutorial guidelines and apply link have been moved to this page
- [x] Link to Financial Aid page (commented out)

## Speaking Resources
- [x] Talk and Tutorial guidelines and apply link  (commented out/moved to other page)
- [x] Update Speaker Green Room  (commented out)
- [x] Update mentor info, as needed, are links still accurate?  (commented out)

## Sponsor
- [x] Update sponsors, as needed

## Become a Sponsor
- [x] Update Other Sponsorship Opportunities table and info

### Note from Kati
Booth info section is commented out

## Throughout
- [x] Update favicon
- [x] Assuming email addresses will stay the same
- [x] Update financial aid policy/timeline, if needed
- [x] Update ticket price policy/timeline, if needed
- [x] Update refund policy/timeline, if needed
- [x] Update hotel policy/timeline, if needed
- [x] Double check info from local organizer group info to see if anything missed
- [ ] Ask local organizer group to review to see if anything missed

## Styleguide
- [x] Styleguide- Michael is working on this

## Event pages?

**Comment by williln** [comment]
@KatherineMichel The organizers section can be checked off as part of #29 

The sponsors section can be checked off as part of #31

**Comment by williln** [comment]
@KatherineMichel "Homepage" can be checked off, "Tickets" can be checked off (refund policy commented out until we get dates), "FAQs" can be checked off, "Schedule" can be checked off.
