### ISSUE TITLE
Accessibility Feedback

### ISSUE THREAD

**Issue by KatherineMichel** [djangocon/2018.djangocon.us#14]
This is a round-up of accessibility issues identified by @lmdragun and @mtrythall 

- [x] 5 SVGs (including logo) need to be accessible for screen readers. According to Lindsey, a title (not alt) tag is required for SVGs. Here is a link provided by Lindsey: https://www.w3.org/WAI/tutorials/images/functional/
- [x] Many icons are in need of alt tags
- [x] In the "A conference with a heart" section on the homepage, the contrast between the background and title is not ideal, but appears to be acceptable due to larger size of text. Michael tried a darker background, black text, and a shadow, but they didn't work well. 
- [x] Text issue with image at the bottom of Why DjangoCon US

**Comment by mtrythall** [comment]
I just added alt tags to the homepage and about. The logo should also now have a title tag.

The social icons at the bottom do not have title tags outside of the shadow DOM. I'm not sure how that works but will look into it. I'd hate to duplicate them, but that's a minor issue.

Will investigate other issues. If you see anymore missing alts LMK.

**Comment by mtrythall** [comment]
Hey @KatherineMichel I believe I got everything here. Can you recheck once the site is deployed please?

**Comment by KatherineMichel** [comment]
@mtrythall I got positive feedback from Lindsey that the accessibility looks better.

**Comment by jefftriplett** [comment]
@KatherineMichel can we close this?

**Comment by KatherineMichel** [comment]
I believe so.
