### ISSUE TITLE
Header / nav jumping 

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2018.djangocon.us#15]
I noticed that the nav/buttons in the header inconsistently drop and look off based on the screen size. It kind of fixes itself and then breaks again based on the width. 

![dcus-screenshot](https://user-images.githubusercontent.com/50527/36558820-e1ba5b6c-17d1-11e8-809a-5b1b77897f4c.png)

The fix might be to drop the nav text size to the next break point.

**Comment by mtrythall** [comment]
Just pushed a fix for this. "Early Bird Pricing Available" was something I
had dropped initially and didn't account for. I just pushed some size
adjustments that will. LMK if you still see the issue.

**Comment by mtrythall** [comment]
@jefftriplett Can you double check and confirm if this is fixed for you? Thanks.

**Comment by jefftriplett** [comment]
LGTM 👍
