### ISSUE TITLE
Experiment with colors on icons for Why DjangoCon US?

### ISSUE THREAD

**Issue by mtrythall** [djangocon/2018.djangocon.us#17]
We may be able to give certain icons a background color, maybe not all. Will experiment.

**Comment by mtrythall** [comment]
@jefftriplett @KatherineMichel Attached is color experimentation. Thoughts?

![screenshot 2018-03-02 22 48 18](https://user-images.githubusercontent.com/84750/36930300-e25da0ce-1e6b-11e8-83a4-5a5b784289d3.png)

**Comment by mtrythall** [comment]
I still feel it distracts. Having only some of them highlighted didn't feel right either when I tried it because I wasn't sure if the ones I was highlighting made sense. For example, "Are you hiring?" or "Two-day Sprints".. That text might change, or may not be important at launch, etc.

**Comment by KatherineMichel** [comment]
@mtrythall I like how they look. To me, they don't seem to distract, because they just seem to fit the overall theme. I've just emailed Kojo about the page content to see if he has some input.

**Comment by mtrythall** [comment]
Ok, works for me. I'll push these up today.

**Comment by mtrythall** [comment]
Ok, I pushed this code then. I'll close this out since you and Joni like it. It's growing on me.
