### ISSUE TITLE
Navigation menu overlap

### ISSUE THREAD

**Issue by craigbruce** [djangocon/2018.djangocon.us#18]
Might be on mobile/iOS only

![c97a6d12-d1cf-4184-83c7-7ddaab184855](https://user-images.githubusercontent.com/1503648/36765484-b1f36470-1bee-11e8-862b-8bba6b0fcac4.jpeg)

**Comment by mtrythall** [comment]
Ah bummer, thought I squashed this. Thanks, we'll take a look.

**Comment by mtrythall** [comment]
Hey @craigbruce Can you give me a bit more context on the iOS version you're using, device, etc? I see it's an iPad, but can you tell me more?

I'm testing in a simulator and this is what I see (attached).

![Uploading Simulator Screen Shot - iPad Air 2 - 2018-02-28 at 21.31.59.png…]()

I have an iPad Mini here on the latest iOS and it's similar.

**Comment by mtrythall** [comment]
Same thing on djangocon.surge.sh

![simulator screen shot - ipad air 2 - 2018-02-28 at 21 35 12](https://user-images.githubusercontent.com/84750/36824225-45212986-1ccf-11e8-89bc-5e7a72242fd1.png)

**Comment by mtrythall** [comment]
Thanks @craigbruce - I'm still trying, here's what I got with an iPad Pro simulator on 11.2.

<img width="1175" alt="screenshot 2018-03-02 21 26 38" src="https://user-images.githubusercontent.com/84750/36929574-84f55aa4-1e60-11e8-9608-f411a37c5809.png">

What's weird about the issue you're having is that the "white block" blocking the menu doesn't exist in that size. It's a full width element, so, I'd expect the entire nav to blocked, not just a portion of it.

I'm getting my hands on a *real* iPad Pro Tuesday (if not sooner), so I'll try again then. Thanks for working with me on it.

**Comment by craigbruce** [comment]
Thanks @mtrythall!

**Comment by mtrythall** [comment]
I'm able to replicate this issue on an actual iPad Pro, but not in a simulator. This makes me think it's hardware/GPU (?) related. Going to dig further. For me, the white block that blocks the menu is random. My hunch is that it's a result of z-index issues and Safari trying to correct, and something glitches on paint.

So, painful to fix. I'll follow up when I have something, hopefully in the coming days.

**Comment by craigbruce** [comment]
That is not pleasant! I’d put this lower priority than other outstanding issues given this only impact a subset of users.

**Comment by jefftriplett** [comment]
I can help test this tonight too. I re-deployed earlier today or last night btw.

**Comment by jefftriplett** [comment]
I'm seeing it now too. It strangely only seems to happen when I click from right to left vs. left to right. No idea if that's helpful or not.

**Comment by mtrythall** [comment]
Possibly a hardware acceleration bug. Added a line or two of code just now that *might* fix it.

Your feedback thus far is helpful, but I'm shooting in the dark without real hardware (I have iPads, just not a Pro anymore).

**Comment by mtrythall** [comment]
Ok, I think my line or two worked:

https://github.com/djangocon/2018.djangocon.us/commit/7530f2c2160660caa8b16df482622d03cc682f05

Can't reproduce on the iPad Pro I have here. @craigbruce can you confirm?

![image uploaded from ios 3](https://user-images.githubusercontent.com/84750/37182946-c32e4d1c-2301-11e8-918a-8bacddd018f6.png)
<img width="1366" alt="image uploaded from ios 2" src="https://user-images.githubusercontent.com/84750/37182947-c34bee94-2301-11e8-95aa-76a2254cbe41.png">
![image uploaded from ios 1](https://user-images.githubusercontent.com/84750/37182948-c35a6122-2301-11e8-859b-c92d55425f46.png)
![image uploaded from ios](https://user-images.githubusercontent.com/84750/37182950-c36b282c-2301-11e8-99f6-1580f5d7df0e.png)

**Comment by mtrythall** [comment]
Same results in Safari (though all iOS browsers should be the same anyway).

**Comment by craigbruce** [comment]
Success! (On Netlify, must be more current than surge now)

**Comment by jefftriplett** [comment]
I checked this early and forgot to follow back up. @mtrythall said he was trying something new on Thursday. 🎉
