### ISSUE TITLE
Child Care RSVP button

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2018.djangocon.us#186]
Nice recommendation via @davidfischer about the "Child Care RSVP" button on https://sustainoss.org/tickets/

**Comment by davidfischer** [comment]
Do you have any thoughts on what the button should do? Should it just be a ticket type in tito? Send an email?

**Comment by jefftriplett** [comment]
The first thing that comes to mind is highlighting childcare and maybe linking to the [update](https://2018.djangocon.us/news/childcare-update/) or someplace more permanent. 

The homepage has three sections [Sponsors, Tutorials & Talks, and CoC]. We could possibly drop the sponsors for more childcare info? 

My brain is very squishy today but open to ideas.
