### ISSUE TITLE
News item colors

### ISSUE THREAD

**Issue by craigbruce** [djangocon/2018.djangocon.us#19]
On the homepage the news items are listed half way down the page, different items get different colors? Is there a significance to the different colors?

**Comment by mtrythall** [comment]
Sponsor related posts are pink. That seems to stand out better with decent readability in a sea of blues. No hard requirement here, just skinning what was there previously.

**Comment by craigbruce** [comment]
From the titles I didn't make that connection, makes sense now - thanks!
