### ISSUE TITLE
Website changes: 

### ISSUE THREAD

**Issue by williln** [djangocon/2018.djangocon.us#204]
Homepage: 

- [x] remove sponsors block 
- [x] replace with link to panel 
- [x] Add "in case of emergency" to panel 
- [x] remove "tickets still on sale" button once sold out 

FAQ page: 

- [x] update tickets on sale 
- [x] add link to Slack channel signup 
- [x] add childcare info 
- [x] update sponsor info as signups closed

**Comment by jefftriplett** [comment]
I updated the description to be ✅ to make measuring progress easier.
