### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by KatherineMichel** [djangocon/2018.djangocon.us#21]
Our contributors section links are not working properly. In addition, I have a couple to add (Joni and Lindsey).

**Comment by jefftriplett** [comment]
What's not working about it? Keep in mind if someone hasn't filed a ticket or submitted something to github then the script won't pick up on them. I think you can just add them to the `.all-contributorsrc` file by hand and then re-run it.

**Comment by KatherineMichel** [comment]
The code is not quite right. The personal links are gone, replaced by avatar pics. Maybe the script just needs to be re-run.

**Comment by jefftriplett** [comment]
Good catch. 

I couldn't figure out how to make the names not break in weird ways so I adjusted the `contributorTemplate` template. Feel free to remove that line and regenerate it if you think it looks better. 

Does Lindsey have a Github account?

**Comment by KatherineMichel** [comment]
This is Lindsey's GitHub: https://github.com/lmdragun/

**Comment by jefftriplett** [comment]
Thank you. Added!
