### ISSUE TITLE
State of Django Panelist info

### ISSUE THREAD

**Issue by oboechick** [djangocon/2018.djangocon.us#212]
Andrew Godwin
(Doesn't want anything but his name up)

Anna Makarudze
DSF Board Member
Django Girls Organizer

Frank Wiles
DSF President
REVSYS President/Founder

Jeff Triplett
DEFNA President 
DjangoCon US Organizer
Revsys Developer
(Pulled from email signature. He may want something else)

Josue Balandrano Coronel
DEFNA Board Member
Celery core member
Author of rmcomplexity.com

Kati Mitchell
Eldarion Web Developer and Community Manager
DEFNA Board Member
DjangoCon US Website Chair

Kojo Idrissa
Jr. Developer
Former DEFNA Board Member
DEFNA North American Ambassador
DjangoCon US Orientation, Sprints and ⚡️Talk Chair

Rachell Calhoun
Django Developer
Django Girls GR and PyLadies GR Organizer
Django Girls Translation Manager & Support Member

**Comment by KatherineMichel** [comment]
Photos
![djangocon-headshot-cropped](https://user-images.githubusercontent.com/4193054/46320514-64211c00-c5a4-11e8-8904-330561aec43d.jpg)
![djangocon-headshot](https://user-images.githubusercontent.com/4193054/46320515-64211c00-c5a4-11e8-84c8-12c6c4562d59.jpg)

**Comment by kojoidrissa** [comment]
I added "Former DEFNA Board Member" to my info, as it seemed relevant.

**Comment by jefftriplett** [comment]
Fixed in #238
