### ISSUE TITLE
:hotel: Fix outdated venue information

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2018.djangocon.us#25]
We need to remove all Hotel RL references along with update our 2018 pricing, order links, photos, etc.

**Comment by jefftriplett** [comment]
I replaced the photo, updated the reservation link, and crossed off a few more t's.

**Comment by williln** [comment]
@jefftriplett Do you know if we have confirmed the accessibility section, specifically: 

- step-free access to all parts of venue, including presentation areas (so we have a ramp available?) 
- Restrooms have stalls with grab bars, but not lowered sinks 
- Service animals have a park nearby where they can be walked 
- hotel doesn't have gender-neutral restrooms 

cc @ossanna16 as Diversity Chair 
 
If we have confirmed those things, then I think this issue can be closed.

**Comment by ossanna16** [comment]
Happy to contact the hotel about this if someone can provide me with their contact info. Thank you!

**Comment by KatherineMichel** [comment]
Closing because duplicate. See #71
