### ISSUE TITLE
:robot: Setup Code Owners to make code reviewers easier

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2018.djangocon.us#27]
GitHub's code owners features look really handy and could save us some time when new pull requests come in: https://blog.github.com/2017-07-06-introducing-code-owners/

If someone has time to take this on, I think it'd be super useful and we can edit as we go.

**Comment by jefftriplett** [comment]
@KatherineMichel would is this one that you would want to tackle?

**Comment by KatherineMichel** [comment]
Sure!

**Comment by jefftriplett** [comment]
I pulled from your branch so that we can play around with this feature while we are getting an uptick in pull requests. Feel free to edit it in `.github/CODEOWNERS` and thank you for getting it started!

**Comment by KatherineMichel** [comment]
Awesome, thanks!
