### ISSUE TITLE
Double Check Important Numbers Info

### ISSUE THREAD

**Issue by KatherineMichel** [djangocon/2018.djangocon.us#36]
Looking through the Important Numbers section, I'm not able to verify that the nearest hospital info is accurate. I can't find it in the linked page and when I google the address it brings up two different results. I think it would be a good idea for this to be verified, along with the other info. Perhaps would be something a local person would have knowledge of?

**Comment by jefftriplett** [comment]
Great catch. Apparently they closed the hospital and Google haven't updated their listing yet. I'll update this after a few meetings unless someone beats me to it. 

> The nearest should be Sharp Memorial Hospital.
> https://www.sharp.com/hospitals/memorial/
> 858-939-3400
> 7901 Frost St.
> San Diego, CA 92123

**Comment by jefftriplett** [comment]
Fixed. Thanks again!

**Comment by KatherineMichel** [comment]
Thank you for taking care of that!
