### ISSUE TITLE
:abcd: Sort Sponsors by their signup date

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2018.djangocon.us#47]
### Expected behavior

Sponsors should be listed by their signup date.

### Actual behavior

Sponsors are sorted by their filenames alphabetically. 

### Steps to repeat behavior

This is visible on the homepage/sponsors page.

### Resolution

The easiest fix is to add their signup date to the filenames and then Jekyll will just do its thing.

**Comment by jefftriplett** [comment]
@williln or @daheats would either of you want to take this one on?

**Comment by williln** [comment]
@jefftriplett Got it! Can probably do it this afternoon.
