### ISSUE TITLE
Sticker/patch designs

### ISSUE THREAD

**Issue by jonitrythall** [djangocon/2018.djangocon.us#56]
PDF submitted for review and waiting for feedback

**Comment by jonitrythall** [comment]
Feedback received ✅Will be preparing PDFs or all designs submitted to be completed by Friday 3/16

**Comment by jonitrythall** [comment]
@moniquemurphy Hi again 👋

Where will you be getting these patches printed again? Just want to confirm their format requirements.

**Comment by adamfast** [comment]
Would it be possible to have a version with the blue/palm tree and the full "DjangoCon US" as well?

**Comment by jonitrythall** [comment]
Hey @adamfast!

I tinkered around with this idea in the beginning and it presented some balance issues with the horizontally long text and vertically long tree.

**Comment by adamfast** [comment]
Ok, thanks @jonitrythall

**Comment by jonitrythall** [comment]
Quick FYI: I am adding sticker order notes to the prepped file folder; also adding them here and will email. 

**Sticker Order Notes**

Palm tree sticker: 

* Style: Circle
* Size: 2 inch round
* Notes to printer: Blue should reach edges

Full logo sticker:

* Style: Rounded corner rectangle
* Size: 2.5 inches wide
* Notes to printer: Yellow background should reach edges

Crab sticker: 

* Style: Die cut with white background
* Size: 1.25 inches wide and heigh
* Notes to printer: White background and outline

Recommended vendor: stickermule.com

**Comment by jonitrythall** [comment]
The patches have been prepared as PDFs and will live in the swag folder.
