### ISSUE TITLE
Slide cover

### ISSUE THREAD

**Issue by jonitrythall** [djangocon/2018.djangocon.us#57]
Need dimensions and specific needs; is this just a slide desk cover image?

**Comment by jonitrythall** [comment]
@moniquemurphy @jefftriplett Any additional details here? Is this for the initial slide in a deck?

**Comment by jefftriplett** [comment]
@adamfast can you confirm the projector dimensions?

**Comment by adamfast** [comment]
@jonitrythall @jefftriplett 1920x1080 is what the Marriott said to built for.
