### ISSUE TITLE
Tote bag design

### ISSUE THREAD

**Issue by jonitrythall** [djangocon/2018.djangocon.us#58]
@moniquemurphy Are there totes you have selected for this so I can grab the dimensions?

**Comment by jonitrythall** [comment]
@moniquemurphy 👋

Also wanted to add that if you have a design in mind for this I can wrap this one up pretty quickly.

**Comment by jonitrythall** [comment]
Going to CC @fcurella here as well in case this is something that has been discussed amongst the team.

**Comment by fcurella** [comment]
Quoting @moniquemurphy from a Slack convo:

> [ the dimensions] don’t really matter, just as long as we have a large .svg file we can resize for whatever vendor as necessary.
>
> let’s say at least U.S. paper size at 600 ppi

**Comment by jonitrythall** [comment]
The dimensions are significant for the reason stated within the comment above. The print area shape drives the design used and I was looking to assist with a possible design scenario that does not already exist as previously discussed on phone calls. 

Going to assume this will be standard logo-based which solid color versions exist in the style guide. Moving this done column and appreciate the assistance!
