### ISSUE TITLE
Banner design

### ISSUE THREAD

**Issue by jonitrythall** [djangocon/2018.djangocon.us#59]

**Comment by jonitrythall** [comment]
@jefftriplett Just need the dimensions for this to move forward 😀

**Comment by fcurella** [comment]
@jonitrythall we have this from last year (https://trello.com/c/AbOUz0Cw/15-banner-stands-2-foot-by-7-foot-tall):

> Banner stands (2 foot by 7 foot tall)
> * One (3 x 1 panels) for the main auditorium stage which includes sponsors logos
> * One reusable panel (1 x 1 panel) which we can put in the 2nd track, hall wall, and dining hall.

**Comment by jonitrythall** [comment]
Appreciate this @fcurella 

I am not able to view that Trello card so just wanted to confirm this is a set of 3 2x7feet panels and a stand alone panel by the same dimensions?

Regarding the logos, will I be adding those or am I putting together a template? Not sure if you have all the sponsors locked down at this point and have SVGs of their logos?

**Comment by jefftriplett** [comment]
@jonitrythall - Here is what we did last year:

- 2 sets of the three-pane wide banner (one sponsor logo on each).
- 4 sets of the pane 3 DjangoCon US logo which is vertical.  

Here are copies of what that looked like:

[QuickWall_template_rev0801_2.pdf](https://github.com/djangocon/2018.djangocon.us/files/1833498/QuickWall_template_rev0801_2.pdf)
[QuickWall_template_rev0801.pdf](https://github.com/djangocon/2018.djangocon.us/files/1833501/QuickWall_template_rev0801.pdf)

You can find SignUp's templates here: https://lawrencesignup.com/download-graphic-templates/ We used the Tension Banner Stand-Premium Template last year.

**Comment by jonitrythall** [comment]
Just making a note here that last year's sponsor logos are within this year's banner design as placeholders and can be swapped out as needed before printing.
