### ISSUE TITLE
Update Style guide to Reflect Brand Direction

### ISSUE THREAD

**Issue by mtrythall** [djangocon/2018.djangocon.us#6]
Dependent upon #3 

This requires updating the style guide to reflect the new brand direction.

**Comment by jefftriplett** [comment]
@mtrythall is this ready for review? 

I looked at http://djangocon.surge.sh/styleguide/ quickly and didn't see anything major. I think we killed `_layouts/home-full.html` but that's easy to fix.

**Comment by mtrythall** [comment]
I see the reference to home-full.html, easy fix.

Yes, it should be good. There wouldn't be anything major since no new patterns (I used the base grid system for Why DjangoCon US? even).

If there is something else with regard to the design you'd like to see, let me know.

**Comment by jefftriplett** [comment]
Thank you. I just didn't want to assume something since it wasn't obvious to me if anything was missing :)
