### ISSUE TITLE
Update Accesibility section

### ISSUE THREAD

**Issue by williln** [djangocon/2018.djangocon.us#71]
**Expected behavior:**
The `/venue/` page contains information about accessibility including: 

- Presence of gender-neutral restrooms and/or confirmation that attendees are welcome to use the restroom they are most comfortable with
- Places to walk service animals and confirmation that they are welcome 
- Accessible restrooms with grab bars/lowered sinks 
- Step-free access to all parts of venue, from parking lot to session rooms and to the stage 

**Actual behavior:**
All this data is TBD. 

**To Fix:**

- Get with chairs to get contact info for venue 
- Contact venue and confirm the above 
- Update `/venue/` page with information

**Comment by ossanna16** [comment]
Here are the responses from the venue:

* Does the venue provide gender-neutral restrooms? - Unfortunately we do not, however we do not discriminate
* Are restrooms equipped with grab bars and lowered sinks? - All public restrooms have accessible stalls 
* Are service animals welcome and are there places nearby to walk them? - Service animals are welcomed and there is grassy area to the left of the hotel.  Also we have a jogging trail along the San Diego River, perfect for pets
* Is there step-free access to all parts of the venue? - Yes 

@williln Do you have suggestions on wording for the restroom part? Something along the lines of "There are no gender neutral restrooms but the venue does not discriminate" sounds odd to me.

**Comment by williln** [comment]
@ossanna16 Last year our phrasing was 

> [Venue] does not provide gender-neutral restrooms. Please use the restroom for the gender with which you identify.

Will that work again for this year?

**Comment by ossanna16** [comment]
Sounds good, thank you! @williln!

**Comment by KatherineMichel** [comment]
Thank you for your help @williln and @ossanna16!
